# Dependabot will run on day 28 of each month at 02:53 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
